@startuml
title Melted Clone Bot
    Caller->Scraper: Specify scrape defs
    Scraper->Twitter: Scrape content
    Scraper<-Twitter: Content
    Caller<-Scraper: Content
    note right of Twitter: Gets all text, images, links, etc.
    Caller->Engine: Process text and images
    note right of Engine: Transformations
    Engine->Caller: New content
    Caller->Twitter: Submit content
@enduml